development:
  adapter: postgresql
  encoding: utf8
  database: tracker_development
  pool: 5
  host: localhost
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tracker_production
  pool: 5
  host: localhost
  username: 
  password: